version: 2

models:
  - name: stg_crm_contacts
    description: Staged CRM contacts with normalized email/phone/name fields
    columns:
      - name: external_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: stg_billing_accounts
    description: Staged billing accounts with parsed first/last name from account_name
    columns:
      - name: external_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]

  - name: stg_support_users
    description: Staged support users with parsed display_name into first/last
    columns:
      - name: external_id
        tests: [not_null, unique]

  - name: stg_identity_input
    description: >
      Unified view of all staged sources. A Snowflake Stream on this view
      captures row-level changes for incremental resolution.
    columns:
      - name: source_system
        tests: [not_null]
      - name: external_id
        tests: [not_null]
